/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ElementStatus = IDL.Variant({
  'complete' : IDL.Null,
  'planned' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ElementType = IDL.Variant({
  'beam' : IDL.Null,
  'slab' : IDL.Null,
  'wall' : IDL.Null,
  'column' : IDL.Null,
  'girder' : IDL.Null,
});
export const PlacedElement = IDL.Record({
  'id' : IDL.Nat,
  'height' : IDL.Float64,
  'status' : ElementStatus,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'yPosition' : IDL.Float64,
  'xPosition' : IDL.Float64,
  'rotationAngle' : IDL.Float64,
  'width' : IDL.Float64,
  'elementType' : ElementType,
});
export const LayoutProject = IDL.Record({
  'name' : IDL.Text,
  'elements' : IDL.Vec(PlacedElement),
});

export const idlService = IDL.Service({
  'addElementToProject' : IDL.Func([IDL.Text, PlacedElement], [], []),
  'createProject' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getProject' : IDL.Func([IDL.Text], [LayoutProject], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(LayoutProject)], ['query']),
  'removeElementFromProject' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateElementInProject' : IDL.Func(
      [IDL.Text, IDL.Nat, PlacedElement],
      [],
      [],
    ),
  'updateFullElementList' : IDL.Func(
      [IDL.Text, IDL.Vec(PlacedElement)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ElementStatus = IDL.Variant({
    'complete' : IDL.Null,
    'planned' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ElementType = IDL.Variant({
    'beam' : IDL.Null,
    'slab' : IDL.Null,
    'wall' : IDL.Null,
    'column' : IDL.Null,
    'girder' : IDL.Null,
  });
  const PlacedElement = IDL.Record({
    'id' : IDL.Nat,
    'height' : IDL.Float64,
    'status' : ElementStatus,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'yPosition' : IDL.Float64,
    'xPosition' : IDL.Float64,
    'rotationAngle' : IDL.Float64,
    'width' : IDL.Float64,
    'elementType' : ElementType,
  });
  const LayoutProject = IDL.Record({
    'name' : IDL.Text,
    'elements' : IDL.Vec(PlacedElement),
  });
  
  return IDL.Service({
    'addElementToProject' : IDL.Func([IDL.Text, PlacedElement], [], []),
    'createProject' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getProject' : IDL.Func([IDL.Text], [LayoutProject], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(LayoutProject)], ['query']),
    'removeElementFromProject' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateElementInProject' : IDL.Func(
        [IDL.Text, IDL.Nat, PlacedElement],
        [],
        [],
      ),
    'updateFullElementList' : IDL.Func(
        [IDL.Text, IDL.Vec(PlacedElement)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };