/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ElementStatus = { 'complete' : null } |
  { 'planned' : null } |
  { 'inProgress' : null };
export type ElementType = { 'beam' : null } |
  { 'slab' : null } |
  { 'wall' : null } |
  { 'column' : null } |
  { 'girder' : null };
export interface LayoutProject {
  'name' : string,
  'elements' : Array<PlacedElement>,
}
export interface PlacedElement {
  'id' : bigint,
  'height' : number,
  'status' : ElementStatus,
  'name' : string,
  'color' : string,
  'yPosition' : number,
  'xPosition' : number,
  'rotationAngle' : number,
  'width' : number,
  'elementType' : ElementType,
}
export interface _SERVICE {
  'addElementToProject' : ActorMethod<[string, PlacedElement], undefined>,
  'createProject' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getProject' : ActorMethod<[string], LayoutProject>,
  'listProjects' : ActorMethod<[], Array<LayoutProject>>,
  'removeElementFromProject' : ActorMethod<[string, bigint], undefined>,
  'updateElementInProject' : ActorMethod<
    [string, bigint, PlacedElement],
    undefined
  >,
  'updateFullElementList' : ActorMethod<
    [string, Array<PlacedElement>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];