/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LayoutProject {
    name: string;
    elements: Array<PlacedElement>;
}
export interface PlacedElement {
    id: bigint;
    height: number;
    status: ElementStatus;
    name: string;
    color: string;
    yPosition: number;
    xPosition: number;
    rotationAngle: number;
    width: number;
    elementType: ElementType;
}
export enum ElementStatus {
    complete = "complete",
    planned = "planned",
    inProgress = "inProgress"
}
export enum ElementType {
    beam = "beam",
    slab = "slab",
    wall = "wall",
    column = "column",
    girder = "girder"
}
export interface backendInterface {
    addElementToProject(projectName: string, element: PlacedElement): Promise<void>;
    createProject(name: string): Promise<void>;
    deleteProject(name: string): Promise<void>;
    getProject(name: string): Promise<LayoutProject>;
    listProjects(): Promise<Array<LayoutProject>>;
    removeElementFromProject(projectName: string, elementId: bigint): Promise<void>;
    updateElementInProject(projectName: string, elementId: bigint, newElement: PlacedElement): Promise<void>;
    updateFullElementList(projectName: string, newElements: Array<PlacedElement>): Promise<void>;
}
import type { ElementStatus as _ElementStatus, ElementType as _ElementType, LayoutProject as _LayoutProject, PlacedElement as _PlacedElement } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addElementToProject(arg0: string, arg1: PlacedElement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addElementToProject(arg0, to_candid_PlacedElement_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addElementToProject(arg0, to_candid_PlacedElement_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getProject(arg0: string): Promise<LayoutProject> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_LayoutProject_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_LayoutProject_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<LayoutProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeElementFromProject(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeElementFromProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeElementFromProject(arg0, arg1);
            return result;
        }
    }
    async updateElementInProject(arg0: string, arg1: bigint, arg2: PlacedElement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateElementInProject(arg0, arg1, to_candid_PlacedElement_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateElementInProject(arg0, arg1, to_candid_PlacedElement_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateFullElementList(arg0: string, arg1: Array<PlacedElement>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFullElementList(arg0, to_candid_vec_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFullElementList(arg0, to_candid_vec_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ElementStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ElementStatus): ElementStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ElementType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ElementType): ElementType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_LayoutProject_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LayoutProject): LayoutProject {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PlacedElement_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlacedElement): PlacedElement {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    height: number;
    status: _ElementStatus;
    name: string;
    color: string;
    yPosition: number;
    xPosition: number;
    rotationAngle: number;
    width: number;
    elementType: _ElementType;
}): {
    id: bigint;
    height: number;
    status: ElementStatus;
    name: string;
    color: string;
    yPosition: number;
    xPosition: number;
    rotationAngle: number;
    width: number;
    elementType: ElementType;
} {
    return {
        id: value.id,
        height: value.height,
        status: from_candid_ElementStatus_n12(_uploadFile, _downloadFile, value.status),
        name: value.name,
        color: value.color,
        yPosition: value.yPosition,
        xPosition: value.xPosition,
        rotationAngle: value.rotationAngle,
        width: value.width,
        elementType: from_candid_ElementType_n14(_uploadFile, _downloadFile, value.elementType)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    elements: Array<_PlacedElement>;
}): {
    name: string;
    elements: Array<PlacedElement>;
} {
    return {
        name: value.name,
        elements: from_candid_vec_n9(_uploadFile, _downloadFile, value.elements)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    complete: null;
} | {
    planned: null;
} | {
    inProgress: null;
}): ElementStatus {
    return "complete" in value ? ElementStatus.complete : "planned" in value ? ElementStatus.planned : "inProgress" in value ? ElementStatus.inProgress : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    beam: null;
} | {
    slab: null;
} | {
    wall: null;
} | {
    column: null;
} | {
    girder: null;
}): ElementType {
    return "beam" in value ? ElementType.beam : "slab" in value ? ElementType.slab : "wall" in value ? ElementType.wall : "column" in value ? ElementType.column : "girder" in value ? ElementType.girder : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LayoutProject>): Array<LayoutProject> {
    return value.map((x)=>from_candid_LayoutProject_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlacedElement>): Array<PlacedElement> {
    return value.map((x)=>from_candid_PlacedElement_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ElementStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ElementStatus): _ElementStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ElementType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ElementType): _ElementType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PlacedElement_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlacedElement): _PlacedElement {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    height: number;
    status: ElementStatus;
    name: string;
    color: string;
    yPosition: number;
    xPosition: number;
    rotationAngle: number;
    width: number;
    elementType: ElementType;
}): {
    id: bigint;
    height: number;
    status: _ElementStatus;
    name: string;
    color: string;
    yPosition: number;
    xPosition: number;
    rotationAngle: number;
    width: number;
    elementType: _ElementType;
} {
    return {
        id: value.id,
        height: value.height,
        status: to_candid_ElementStatus_n3(_uploadFile, _downloadFile, value.status),
        name: value.name,
        color: value.color,
        yPosition: value.yPosition,
        xPosition: value.xPosition,
        rotationAngle: value.rotationAngle,
        width: value.width,
        elementType: to_candid_ElementType_n5(_uploadFile, _downloadFile, value.elementType)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ElementStatus): {
    complete: null;
} | {
    planned: null;
} | {
    inProgress: null;
} {
    return value == ElementStatus.complete ? {
        complete: null
    } : value == ElementStatus.planned ? {
        planned: null
    } : value == ElementStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ElementType): {
    beam: null;
} | {
    slab: null;
} | {
    wall: null;
} | {
    column: null;
} | {
    girder: null;
} {
    return value == ElementType.beam ? {
        beam: null
    } : value == ElementType.slab ? {
        slab: null
    } : value == ElementType.wall ? {
        wall: null
    } : value == ElementType.column ? {
        column: null
    } : value == ElementType.girder ? {
        girder: null
    } : value;
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PlacedElement>): Array<_PlacedElement> {
    return value.map((x)=>to_candid_PlacedElement_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
